services:
  - type: web
    name: intellex-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 22
    autoDeploy: true
